version: '3.8'

services:
  app-hub:
    build: .
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    # ถ้าต้องการ volume สำหรับ persistent data
    # volumes:
    #   - ./data:/app/data
    networks:
      - app-network

  # ถ้าต้องการ Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app-hub
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 